### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by gftruj** [donmccurdy/webvr-experiments#2]
Hello, trying to make the examples work @rawgit i get the 404 bundle.js not found. Shouldn't there be index.js included instead of bundle.js, or am I missing something ?

**Comment by donmccurdy** [comment]
Hi @gftruj — you'll need to build the code locally, it doesn't work with rawgit right now. To create a bundle for the first example:

```
npm install
npm run dev:1
```

There are three bundles, one for each example. See [package.json:L8-10](https://github.com/donmccurdy/webvr-experiments/blob/master/package.json#L8-L10).
