### ISSUE TITLE
GitHub pages?

### ISSUE THREAD

**Issue by EliasHasle** [donmccurdy/webvr-experiments#3]
Hello, Don! Any chance that you will enable GitHub pages for this repository, so that everyone can test the experiments online? If it works as for me, it will get the address donmccurdy.github.io/webvr-experiments (and only directories with index files will work)

**Comment by donmccurdy** [comment]
Hey! Sorry, at the moment these aren't experiments I want to host for demos. Each demo also involves a build (w/ Budo usually) so compiled code would need to be checked into the repository.

**Comment by EliasHasle** [comment]
Thanks for your answer. I tried to google Budo, and was a bit confused... But eventually found it. So you also have some server-side code. Then GitHub pages won't work anyway, I think. OK. I am hoping to see your demos live in the future, then. (No rush.) 😃

**Comment by donmccurdy** [comment]
Not serverside exactly, just a local build step, and I don't really want to check in the built code... for the demos that have a `package.json` the steps to start them would be:

```
npm install && npm run dev
```

For those that don't, it would be:

```
npm install --global budo
budo index.js:bundle.js .
```
